"""create classes and assignments tables

Revision ID: 4916752d6078
Revises: a54dbc52c117
Create Date: 2025-10-31 10:45:59.607004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import sqlmodel.sql.sqltypes 



# revision identifiers, used by Alembic.
revision: str = '4916752d6078'
down_revision: Union[str, Sequence[str], None] = 'a54dbc52c117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('essay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'assignments', ['assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assignment_id')

    op.drop_table('assignments')
    op.drop_table('classes')
    # ### end Alembic commands ###
