"""changed feedback and suggestion field to TEXT data type

Revision ID: 5de0bf374d18
Revises: 835a74193ca3
Create Date: 2025-11-01 09:22:14.135322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import sqlmodel.sql.sqltypes 

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5de0bf374d18'
down_revision: Union[str, Sequence[str], None] = '835a74193ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criterion_essay_grade', schema=None) as batch_op:
        batch_op.alter_column('feedback',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('suggestion',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)

    with op.batch_alter_table('overall_essay_grade', schema=None) as batch_op:
        batch_op.alter_column('feedback',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)
        batch_op.alter_column('suggestion',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_essay_grade', schema=None) as batch_op:
        batch_op.alter_column('suggestion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('feedback',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('criterion_essay_grade', schema=None) as batch_op:
        batch_op.alter_column('suggestion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('feedback',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
