"""add total_score and rename max score

Revision ID: 835a74193ca3
Revises: 4916752d6078
Create Date: 2025-11-01 08:57:38.925325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
import sqlmodel.sql.sqltypes 

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '835a74193ca3'
down_revision: Union[str, Sequence[str], None] = '4916752d6078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('criterion_essay_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('label')

    with op.batch_alter_table('overall_essay_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_max_score', sa.Integer(), nullable=False))
        batch_op.drop_column('max_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overall_essay_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_score', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('total_max_score')
        batch_op.drop_column('total_score')

    with op.batch_alter_table('criterion_essay_grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
